before_install:
  sudo apt-get update -qq
  sudo apt-get install -qq protobuf-compiler libprotobuf-dev
language: ruby
gemfile:
  - Gemfile
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
matrix:
  allow_failures:
    - rvm: rbx-2.1.1

